import pandas as pd
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
from plotly.subplots import make_subplots


pio.templates.default = "plotly_white"

df = pd.read_csv("supply_chain_data.csv")
print(df.head())  


fig = make_subplots(
    rows=3, cols=2, 
    subplot_titles=(
        "Product Quantities by Product Type", 
        "Sales by Product Type", 
        "Total Revenue by Shipping Carrier",
        "Revenue Generated by each SKU", 
        "Order Quantity of each SKU", 
        "Shipping cost according to carrier"
    ),
    vertical_spacing=0.1,
    horizontal_spacing=0.1,
    specs=[
        [{"type": "xy"}, {"type": "domain"}],
        [{"type": "xy"}, {"type": "xy"}], 
        [{"type": "xy"}, {"type": "xy"}]   
    ]
)


fig.add_trace(
    go.Bar(x=df['best selling products'], y=df['Number of products sold'], name="Product Quantities"),
    row=1, col=1
)


product_type = df.groupby('best selling products')['Number of products sold'].sum().reset_index()


fig.add_trace(
    go.Pie(
        labels=product_type['best selling products'], 
        values=product_type['Number of products sold'], 
        name="Sales by Product Type",
        hole=0.5,
        textinfo='percent+label'
    ),
    row=1, col=2
)


total_revenue = df.groupby('Shipping carriers')['Revenue generated'].sum().reset_index()


fig.add_trace(
    go.Bar(x=total_revenue['Shipping carriers'], y=total_revenue['Revenue generated'], name="Total Revenue by Shipping Carrier"),
    row=2, col=1
)


fig.add_trace(
    go.Scatter(x=df['SKU'], y=df['Revenue generated'], mode='lines', name="Revenue by SKU"),
    row=2, col=2
)


fig.add_trace(
    go.Scatter(x=df['SKU'], y=df['Order quantities'], mode='lines', name="Order Quantity by SKU"),
    row=3, col=1
)


ship_cost = df.groupby('Shipping carriers')['Shipping costs'].sum().reset_index()
fig.add_trace(
    go.Bar(x=ship_cost['Shipping carriers'], y=ship_cost['Shipping costs'], name="Shipping Cost by Carrier"),
    row=3, col=2
)


fig.update_layout(
    height=900, 
    width=1900, 
    title_text="Supply Chain Data Visualizations", 
    showlegend=False
)

fig.show()
